import type { Plan } from "@/types";

export const plans: Plan[] = [
  {
    id: "free",
    name: "مجاني",
    description: "مثالية للبدء واستكشاف المنصة. انشر أول عقار لك مجانًا.",
    priceMonthly: 0,
    priceYearly: 0,
    features: [
      "نشر عقار واحد ✓",
      "صور رئيسية للعقار ✓",
      "إمكانية نشر أكثر من عقار ✕",
      "صور تفصيلية للعقار ✕", 
      "مساعد الوصف بالذكاء الاصطناعي ✕",
      "دعم محدود ✓",
    ],
    maxListings: 1,
    imageLimitPerProperty: 1, 
    aiAssistantAccess: false,
    cta: "ابدأ مجاناً",
  },
  {
    id: "vip",
    name: "VIP",
    description: "الأكثر شيوعًا للمستخدمين الجادين. احصل على أدوات متقدمة للتميز.",
    priceMonthly: 0,
    priceYearly: 0,
    features: [
      "نشر عقار واحد ✓",
      "إمكانية نشر أكثر من عقار ✕",
      "صور رئيسية للعقار ✓",
      "صور تفصيلية للعقار ✓",
      "مساعد الوصف بالذكاء الاصطناعي (محدود) ✓",
      "دعم ذو أولوية ✓",
    ],
    maxListings: 1,
    imageLimitPerProperty: 5,
    aiAssistantAccess: true,
    cta: "اختر VIP",
  },
  {
    id: "vip_plus_plus",
    name: "VIP++",
    description: "الحل الأمثل للوكالات العقارية والمحترفين. لا حدود لطموحاتك.",
    priceMonthly: 0,
    priceYearly: 0,
    features: [
      "نشر عدد غير محدود من العقارات ✓",
      "صور رئيسية للعقار ✓",
      "صور تفصيلية للعقار ✓",
      "مساعد الوصف بالذكاء الاصطناعي (كامل) ✓✓",
      "ظهور مميز للعقارات ✓✓",
      "دعم فوري ✓✓",
    ],
    maxListings: Infinity,
    imageLimitPerProperty: 4,
    aiAssistantAccess: true,
    cta: "اختر VIP++",
  },
];
